kind: pipeline
type: kubernetes
name: build-amd64
platform:
  arch: amd64
node_selector:
  kubernetes.io/arch: amd64

volumes:
- name: fedhq-ca-crt
  config_map:
    name: fedhq-ca-crt
    default_mode: 420     # same as 644 in octal, or u+w,a+r
    optional: false

steps:
  - name: build amd64
    image: quay.io/buildah/stable
    privileged: true
    volumes:
    - name: fedhq-ca-crt
      path: /etc/ssl/certs2/
    commands:
      - scripts/setupEnvironment.sh
      - buildah bud --network host -t "registry.cloud.federationhq.de/fhem:latest-amd64"  --arch amd64 .
      - buildah push --all registry.cloud.federationhq.de/fhem:latest-amd64
---
kind: pipeline
type: kubernetes
name: build-arm64
platform:
  arch: arm64
node_selector:
  kubernetes.io/arch: arm64

volumes:
- name: fedhq-ca-crt
  config_map:
    name: fedhq-ca-crt
    default_mode: 420     # same as 644 in octal, or u+w,a+r
    optional: false

steps:
  - name: build arm64
    image: quay.io/buildah/stable
    privileged: true
    volumes:
    - name: fedhq-ca-crt
      path: /etc/ssl/certs2/
    commands:
      - scripts/setupEnvironment.sh
      - buildah bud --network host -t "registry.cloud.federationhq.de/fhem:latest-arm64" --arch arm64 .
      - buildah push --all registry.cloud.federationhq.de/fhem:latest-arm64
---
kind: pipeline
type: kubernetes
name: push
node_selector:
  kubernetes.io/arch: amd64
       
volumes:
- name: fedhq-ca-crt
  config_map:
    name: fedhq-ca-crt
    default_mode: 420     # same as 644 in octal, or u+w,a+r
    optional: false

steps:
  - name: push
    image: quay.io/buildah/stable
    privileged: true
    volumes:
    - name: fedhq-ca-crt
      path: /etc/ssl/certs2/
    commands:
      - scripts/setupEnvironment.sh
      - buildah manifest create registry.cloud.federationhq.de/fhem:latest registry.cloud.federationhq.de/fhem:latest-arm64 registry.cloud.federationhq.de/fhem:latest-amd64
      - buildah manifest push registry.cloud.federationhq.de/fhem:latest docker://registry.cloud.federationhq.de/fhem:latest 
depends_on:
  - build-amd64
  - build-arm64


---
kind: pipeline
type: kubernetes
name: push-docker-hub
node_selector:
  kubernetes.io/arch: amd64
       
volumes:
- name: fedhq-ca-crt
  config_map:
    name: fedhq-ca-crt
    default_mode: 420     # same as 644 in octal, or u+w,a+r
    optional: false

steps:
  - name: push
    image: quay.io/buildah/stable
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    privileged: true
    volumes:
    - name: fedhq-ca-crt
      path: /etc/ssl/certs2/
    commands:
      - scripts/setupEnvironment.sh
      - buildah login -u $${USERNAME} -p $${PASSWORD} hub.docker.com
      - buildah manifest push registry.cloud.federationhq.de/fhem:latest docker://hub.docker.com/byterazor/fhem:latest 
      - buildah manifest rm registry.cloud.federationhq.de/fhem:latest
depends_on:
  - push

---
kind: secret
name: username
get:
  path: docker
  name: username

---
kind: secret
name: password
get:
  path: docker
  name: secret